import Head from "next/head";
import { gql, useQuery, useMutation } from "@apollo/client";
import Link from "next/link";
import Blog from "../../components/Blog";
import Header from "../../components/Header"
import styles from '../../styles/pages/posts.module.scss';
import Footer from "../../components/Footer"
import RecentPost from "../../components/RecentPost"
import Category from "../../components/Category"



const AllLinksQuery = gql`query UPDATE_QRY($first: Int, $after: String) {
    posts(first: $first, after: $after) {
        pageInfo {
            hasPreviousPage
            hasNextPage
            endCursor
            startCursor
        }
        nodes {
            title
            excerpt
            slug
            featuredImage {
                node {
                    sourceUrl
                }
            }
        }
    }
}`;


function Home() {
    const { data, loading, error, fetchMore } = useQuery(AllLinksQuery, {
        variables: { first: 9 },
    });

    if (loading) return <p>Loading...</p>;
    if (error) return <p>Oh no... {error.message}</p>;

    const { endCursor, hasNextPage } = data.posts.pageInfo;

    return (
        <>
            <Header />
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className="content content-page">
                    <div className="blogWrap">
                        <div className="blogContainer">

                            <Blog
                                posts={data?.posts?.nodes}
                                headingLevel="h2"
                                postMainTitleLevel="h1"
                                postTitleLevel="h4"
                                id={styles.post_list}
                            />
                            <div className="text-center">
                                {hasNextPage ? (
                                    <button
                                        className="px-4 py-2 bg-blue-500 text-white rounded my-10"
                                        onClick={() => {
                                            fetchMore({
                                                variables: { after: endCursor },
                                                updateQuery: (prevResult, { fetchMoreResult }) => {
                                                    fetchMoreResult.posts.nodes = [
                                                        ...prevResult.posts.nodes,
                                                        ...fetchMoreResult.posts.nodes,
                                                    ];
                                                    return fetchMoreResult;
                                                },
                                            });
                                        }}
                                    >
                                        Load More
                                    </button>
                                ) : (
                                    <p className="my-10 text-center font-medium">
                                        You've reached the end!{" "}
                                    </p>
                                )}
                            </div>
                        </div>
                        <div className="blogNav">
                            <RecentPost posts={data?.posts?.nodes} />
                            {/* <Category categories={categories?.nodes} /> */}
                        </div>
                    </div>

                </main>
                <Footer />

                {/* <main className={styles.main}>
            {posts.map((value, key) => (
                <div key={key}>
                    <div>{value?.title}</div>
                    <div>{value?.content}</div>
                </div>
            ))}
        </main> */}


            </div>
        </>
    );
}

export default Home;