import Head from 'next/head'
import Image from 'next/image'
import { client } from '../../lib/apollo';
import { gql } from "@apollo/client";
import Blog from "../../components/Blog"
import Header from "../../components/Header"
import Footer from "../../components/Footer"
import Category from "../../components/Category"
import styles from '../../styles/pages/posts.module.scss';
import BLOG_QRY from "../../lib/BlogsQry";


export default function Home({ posts,categories }) {
    return (
        <>
            <Header />
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className="content content-page">
                    <div className="blogWrap">
                        <div className="blogContainer">
                            <Blog
                                posts={posts}
                                headingLevel="h2"
                                postMainTitleLevel="h1"
                                postTitleLevel="h4"
                                id={styles.post_list}
                            />

                            {/* <Pagination pageInfo={posts.pageInfo} basePath="/blog" /> */}
                        </div>
                        <div className="blogNav">
                            {/* <RecentPost /> */}
                            <Category categories={categories?.nodes} />
                        </div>
                    </div>
                </main>
                <Footer />
            </div>
        </>
    )
}

export async function getStaticProps() {

    const response = await client.query({
        query: BLOG_QRY
    });

    const posts = response?.data?.posts?.nodes;
    const categories = response.data?.categories

    return {
        props: {
            posts,
            categories
        }
    }
}