import Link from "next/link";
import { useRouter } from "next/router";

export default function ServerSitemap() {
    return (
        <>
      <div className="p-10">
        <div>
          <h4>XML Sitemap</h4>
          <p>
            Generated by Yoast SEO, this is an XML Sitemap, meant for
            consumption by search engines.
          </p>
          <p>
            You can find more information about XML sitemaps on sitemaps.org.
          </p>
          <p>This XML Sitemap Index file contains 17 sitemaps.</p>
        </div>
        <section>
          <div className="grid grid-cols-3 gap-4">
            <div className="col-span-2">Sitemap</div>
          </div>
          <div className="border-2"></div>
          <ul className="sitemapListNav">
            <li>
              <Link href="/post-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/post-sitemap1.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post-sitemap1.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/post-sitemap2.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post-sitemap2.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/post-sitemap3.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post-sitemap3.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/post-sitemap4.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post-sitemap4.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/post-sitemap5.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post-sitemap5.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/page-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/page-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="#">
                <a>{process.env.NEXT_PUBLIC_URL}/attachment-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/solutions-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/solutions-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/problems-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/problems-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/products_services-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/products_services-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/team_members-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/team_members-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/press_releases-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/press_releases-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="https://kapitus.com/careers-sitemap.xml">
                <a target="_blank">{process.env.NEXT_PUBLIC_URL}/careers-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/kap_events-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/kap_events-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/faqs-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/faqs-sitemap.xml</a>
              </Link>
            </li>
            {/* <li>
              <Link href="/press_coverage-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/press_coverage-sitemap.xml</a>
              </Link>
            </li> */}
            <li>
              <Link href="/guide-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/guide-sitemap.xml</a>
              </Link>
            </li>
            
            <li>
              <Link href="/category-sitemap.xml" passHref>
                <a>{process.env.NEXT_PUBLIC_URL}/category-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/post_tag-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/post_tag-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/department-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/department-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/media_center-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/media_center-sitemap.xml</a>
              </Link>
            </li>
            <li>
              <Link href="/author-sitemap.xml">
                <a>{process.env.NEXT_PUBLIC_URL}/author-sitemap.xml</a>
              </Link>
            </li>
          </ul>
        </section>
      </div>
    </>
    )
}
